dc_name: DC1

spine:
  defaults:
    loopback_ipv4_pool: 10.1.0.0/24
    bgp_defaults:
      - 'distance bgp 150 200 200'
      - 'graceful-restart restart-time 300'
      - 'graceful-restart'
    evpn_role: none
  node_groups:
    - group: dc1-spinepair
      bgp_as: 65000
      nodes:
        - name: dc1-spine1
          id: 0
          mgmt_ip: 10.0.0.1/24
        - name: dc1-spine2
          id: 1
          mgmt_ip: 10.0.0.2/24

l3leaf:
  defaults:
    virtual_router_mac_address: 00:11:22:33:44:55
    loopback_ipv4_pool: 10.1.0.0/24
    vtep_loopback_ipv4_pool: 10.3.0.0/24
    loopback_ipv4_offset: 2
    uplink_ipv4_pool: 10.2.0.0/24
    bgp_defaults:
      - 'distance bgp 150 200 200'
      - 'graceful-restart restart-time 300'
      - 'graceful-restart'
    spanning_tree_priority: 4096
    spanning_tree_mode: mstp
    mlag_peer_l3_ipv4_pool: 10.4.0.0/24
    mlag_peer_ipv4_pool: 10.5.0.0/24
    uplink_interfaces: [ Ethernet49/1, Ethernet50/1 ]
    uplink_switches: [ dc1-spine1, dc1-spine2 ]
    mlag_interfaces: [ Ethernet55/1, Ethernet56/1 ]
    evpn_role: client
    evpn_route_servers: [ dc1-leaf1, dc1-leaf2 ]
  node_groups:
    - group: dc1-leafpair1
      bgp_as: 65001
      evpn_role: server
      evpn_route_servers: [ dc2-leaf1, dc2-leaf2 ]
      nodes:
        - name: dc1-leaf1
          id: 0
          mgmt_ip: 10.0.0.3/24
          uplink_switch_interfaces: [ Ethernet1/1, Ethernet1/1 ]
        - name: dc1-leaf2
          id: 1
          mgmt_ip: 10.0.0.4/24
          uplink_switch_interfaces: [ Ethernet2/1, Ethernet2/1 ]
    - group: dc1-leafpair2
      bgp_as: 65002
      nodes:
        - name: dc1-leaf3
          id: 2
          mgmt_ip: 10.0.0.5/24
          uplink_switch_interfaces: [ Ethernet3/1, Ethernet3/1 ]
        - name: dc1-leaf4
          id: 3
          mgmt_ip: 10.0.0.6/24
          uplink_switch_interfaces: [ Ethernet4/1, Ethernet4/1 ]
