tenants:
  - name: AcmeCorp
    mac_vrf_vni_base: 10000

    l2vlans:
      - id: 10
        name: "ISP1"
      - id: 20
        name: "ISP2"

    vrfs:
      - name: "InbandMgmt"
        vrf_vni: 1

        static_routes:
          - destination_address_prefix: 0.0.0.0/0
            gateway: 10.10.0.254
            nodes: [ dc1-leaf1, dc1-leaf2, dc2-leaf1, dc2-leaf2 ]

        svis:
          - id: 100
            name: "InbandMgmt"
            enabled: true
            mtu: 9000
            nodes:
              - node: "dc1-spine1"
                ip_address: 10.10.0.1/24
              - node: "dc1-spine2"
                ip_address: 10.10.0.2/24
              - node: "dc1-leaf1"
                ip_address: 10.10.0.3/24
              - node: "dc1-leaf2"
                ip_address: 10.10.0.4/24
              - node: "dc1-leaf3"
                ip_address: 10.10.0.5/24
              - node: "dc1-leaf4"
                ip_address: 10.10.0.6/24
              - node: "dc2-spine1"
                ip_address: 10.10.0.7/24
              - node: "dc2-spine2"
                ip_address: 10.10.0.8/24
              - node: "dc2-leaf1"
                ip_address: 10.10.0.9/24
              - node: "dc2-leaf2"
                ip_address: 10.10.0.10/24
              - node: "dc2-leaf3"
                ip_address: 10.10.0.11/24
              - node: "dc2-leaf4"
                ip_address: 10.10.0.12/24

      - name: "Kubernetes"
        vrf_vni: 2

        static_routes:
          - destination_address_prefix: 0.0.0.0/0
            gateway: 10.20.0.254
            nodes: [ dc1-leaf1, dc1-leaf2, dc2-leaf1, dc2-leaf2 ]

        svis:
          - id: 200
            name: "Linknet Kubernetes FW"
            enabled: true
            mtu: 9000
            ip_address_virtual: "10.20.0.1/24"

          - id: 201
            name: "Kubernetes1"
            enabled: true
            mtu: 9000
            ip_address_virtual: "10.21.0.1/24"
            ip_helpers:
              - ip_helper: 10.20.0.250

          - id: 202
            name: "Kubernetes2"
            enabled: true
            mtu: 9000
            ip_address_virtual: "10.22.0.1/24"
            ip_helpers:
              - ip_helper: 10.20.0.250

      - name: "Proxmox"
        vrf_vni: 3

        static_routes:
          - destination_address_prefix: 0.0.0.0/0
            gateway: 10.30.0.254
            nodes: [ dc1-leaf1, dc1-leaf2, dc2-leaf1, dc2-leaf2 ]

        svis:
          - id: 300
            name: "Linknet Proxmox FW"
            enabled: true
            mtu: 9000
            ip_address_virtual: "10.30.0.1/24"

          - id: 301
            name: "Proxmox1"
            enabled: true
            mtu: 9000
            ip_address_virtual: "10.31.0.1/24"
            ip_helpers:
              - ip_helper: 10.30.0.250

          - id: 302
            name: "Proxmox2"
            enabled: true
            mtu: 9000
            ip_address_virtual: "10.32.0.1/24"
            ip_helpers:
              - ip_helper: 10.30.0.250